---
name: Acceptance Test With Pytest
on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions: read-all

jobs:
  acceptance-test:
    name: Run pytest Acceptance test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Download test data
        run: |
          gh release download \
          --pattern 'OTCamera19_FR20_2023-05-24_06-00-00_11-45-00.zip' \
          --pattern 'OTCamera19_FR20_2023-05-24_00-00-00.zip' \
          -R platomo/OpenTrafficCam-testdata -D tests/data
        env:
          GH_TOKEN: ${{ secrets.PLATOMO_OTC_TESTDATA_ACCESS }}
      - name: Unzip test data
        run: |
          cd tests/data
          unzip ./\*.zip
          rm ./*.zip
          cd ..
      - name: Run acceptance tests
        uses: platomo/test-python-app-action@v4
        timeout-minutes: 20
        with:
          py-version: 3.12
          package-path: OTAnalytics
          test-path: tests/acceptance
          playwright-required: true
