---
# This workflow will install Python dependencies, run tests

name: Create Distribution

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11" ]
    uses: platomo/GitHub-workflows/.github/workflows/reusable-python-tests.yml

  create_distributions:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10" ]
    uses: platomo/GitHub-workflows/.github/workflows/reusable-create-nightly.yml
    with:
      repo-token: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
  create_nightly:
    needs: create_distributions
    runs-on: ${{ matrix.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: True
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]
    uses: platomo/GitHub-workflows/.github/workflows/reusable-create-nightly.yml
    with:
      repo-token: ${{ secrets.PLATOMO_BUILDER_ACCESS }}
